remote_theme: 256-Foundation/midnight-theme
title: NEWS256
description: A monthly newsletter supported by Proto
github:
  repository_url: https://256foundation.substack.com/
  owner_url: https://256foundation.org
